dist: bionic

language: generic

addons:
  apt:
    packages:
      # required to build
      - cm-super
      - texlive
      - texlive-lang-cyrillic
      - texlive-science
      - texlive-latex-extra
      - latexmk

install:
    # download a newer latexmk
    - curl https://ctan.mirror.norbert-ruehl.de/support/latexmk.zip -o /tmp/latexmk.zip
    - unzip /tmp/latexmk.zip latexmk/latexmk.pl

script: |
    if [[ "$TRAVIS_BRANCH" == "devel" ]]; then
        make LATEXMK="./latexmk/latexmk.pl" build
    else
        make LATEXMK="./latexmk/latexmk.pl" LATEXMK_FLAGS="-Werror" style build
    fi

before_deploy: |
    # rename the pdf file
    cp main.pdf bulatov2.pdf
    # set up git user name and tag this commit
    git config --local user.name "travis"
    git config --local user.email "travis"
    TRAVIS_TAG=latest
    [[ "$TRAVIS_BRANCH" == "devel" ]] && TRAVIS_TAG=devel-latest
    export TRAVIS_TAG
    echo "Branch is: $TRAVIS_BRANCH"
    echo "Using tag: $TRAVIS_TAG"
    git tag -f $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: "SLYtB9Xhv7vrBtZOsqdepktfBXsR/bQ5wbCEOeqAfL9CWN8KVeB5Lp6S05CxSVqPVk3ik368hqhpZdiO/qaoRAA8+UKVKfCoScFBlCHBLa/NPIvWGu8h4LVJJe8Z4hV7z3QWAj08mP/rwqxUSDjNo8c/tsLFxtQVd1XTvKFcyLQnOKRiUPjRVmT82bAEkJVwwzTewcBnQfjgO2q14kAavlGMrlVF5egs98oz2LPQYWmxiRjvjIh7POe73r3frR+2rJezVyin0SqojIJS0zngePaeNThJVTqB980w3yqytuSR+MBOi52c2rV4jiZGQSxGJWiyCx5W/23OIVCRSEOQbw6gq52OSpcfNmXNtnh9HoQXgHiYVAy/hKGTGdAUdcvU6wkLk67hFKrVqeMlDFrrUlxnCnOyTckSluvTAFiGpQfCKaqMhWBnMbhWEw45Ko0IL9JdC+hSo31OHyd+BUEb1/X7tYgriWA/plUi+CsQPvnCP0ffpSC869oI4iuAQJciw3JgXZa37LbjYul3ZGzl6U3asDekkYbBc6aKcLIbLRbmbX1Sk/rTomWuTKwTKWs/IEEyOvUeiWQYxRY0dLB5fToh2kyKWCzFRsJ2HQZgoM48L+Qgen+gcFylDSY1DKvyrIMQaI3Yv4Ue2rXrpxD/4eLcc6qIyNgOa8GmjxqMVH8="
  file:
    - "bulatov2.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    branches:
      only:
        - master
        - devel

tags:
  except:
    - latest
